export const githubDummyData = {
  "login": "BlueEagle",
  "id": 6562992,
  "node_id": "MDQ6VXNlcjY1NjI5OTI=",
  "avatar_url": "https://avatars0.githubusercontent.com/u/6562992?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/BlueEagle",
  "html_url": "https://github.com/BlueEagle",
  "followers_url": "https://api.github.com/users/BlueEagle/followers",
  "following_url": "https://api.github.com/users/BlueEagle/following{/other_user}",
  "gists_url": "https://api.github.com/users/BlueEagle/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/BlueEagle/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/BlueEagle/subscriptions",
  "organizations_url": "https://api.github.com/users/BlueEagle/orgs",
  "repos_url": "https://api.github.com/users/BlueEagle/repos",
  "events_url": "https://api.github.com/users/BlueEagle/events{/privacy}",
  "received_events_url": "https://api.github.com/users/BlueEagle/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Collin Ballou",
  "company": null,
  "blog": "Balloucollin.dev",
  "location": "Utah",
  "email": null,
  "hireable": true,
  "bio": "Writing many things.\r\n\r\nStudent at Lambda School.\r\n\r\nPython is my side hustle.",
  "twitter_username": null,
  "public_repos": 57,
  "public_gists": 2,
  "followers": 5,
  "following": 27,
  "created_at": "2014-02-01T18:28:57Z",
  "updated_at": "2020-07-16T19:22:30Z"
}